export const colors = {
  dark: {
    brandMain: "#333",
    backgroundMain: "#1A202C",
    backgroundSecondary: "#000",
    fontMain: "#FFF",
    fontSecondary: "#1A202C",
  },
  brandMain: "#fe6ab4",
  fontMain: "#000",
  fontSecondary: "#ffffff",
  backgroundMain: "#ffffff",
  backgroundSecondary: "#efefef",
  backgroundTertiary: "#979797",
  costInGold: "#ff884b",
  costInRoses: "#FF1E00",
  genderMale: "#1C6DD0",
  genderFemale: "#FF78F0",
  genderNeutral: "#59CE8F",
  rarityCommon: "#BA704F",
  rarityRare: "#CE5959",
  rarityEpic: "#a31acb",
  rarityLegendary: "#e27802",
  itemType: "#59CE8F",
  goodAura: "#59CE8F",
  evilAura: "#FF1E00",
  unknownAura: "#ff884b",
  randomAura: "#a31acb",
  positive: "#59CE8F",
  negative: "#FF1E00",
};
